In [1]:
import matplotlib.pyplot as plt
import pandas as pd

%matplotlib inline

In [2]:
df_raw = pd.read_csv('../results/over_smoothing.csv')
models = ['GAT', 'GCN', 'MLP', 'g2-MLP']
df = df_raw[['num_layers'] + models]

In [3]:
df_mean = df.groupby(['num_layers']).agg('mean')
df_mean

                  GAT        GCN        MLP     g2-MLP
num_layers
4           82.435234  80.842844  82.530775  99.531331
8           85.084230  80.693114  82.970030  99.662898
12          83.510422  79.961670  83.067067  99.689350
16          79.539979  78.262997  83.080772  99.699493
20          73.782353  74.484533  83.126373  99.704700
24          73.514252  72.801060  83.102734  99.700391

In [4]:
df_std = df.groupby(['num_layers']).agg('std')
df_std

                 GAT       GCN       MLP    g2-MLP
num_layers
4           0.589346  0.132747  0.012823  0.018307
8           0.538360  0.322166  0.012899  0.008760
12          1.864513  0.726863  0.015326  0.007406
16          3.812715  1.609076  0.018779  0.013000
20          1.211128  0.785786  0.036188  0.013964
24          1.111541  0.675653  0.017731  0.006226

In [5]:
fig = plt.figure(figsize=(15,10))
for k in models:
    plt.errorbar(
        df_mean.index,
        df_mean[k],
        yerr=df_std[k],
        capsize=5,  # エラーバーの横線の長さ
        label=k,
    )
plt.title('Relationship between micro-F1 score on PPI dataset and number of layers.', fontsize=15)
plt.xlabel('number of layers', fontsize=15)
plt.ylabel('micro-f1 score on PPI dataset', fontsize=15)
plt.xticks(df_mean.index, df_mean.index)
plt.ylim(70, 100)
plt.legend()
fig.savefig('../results/over_smoothing.jpg')
plt.close()